---
# Semantic versioning labels
- name: semver:breaking
  description: "Major: Update contains a breaking change"
  color: 3868a8
- name: semver:feature
  description: "Minor: Update contains a feature addition"
  color: 648dc4
- name: semver:patch
  description: "Patch: Update contains a fix"
  color: 9dc2f2

# Feature/improvement labels
- name: feature
  description: New feature or enhancement
  color: 0075ca
- name: docs
  description: Improvements or additions to documentation
  color: 0075ca
- name: test
  description: Improvements or additions to tests
  color: 0075ca

# Administrative label
- name: chore
  description: Changes that don't affect functionality
  color: 4e4c5c

# Non-functional enhancement labels
- name: ci
  description: Enhancements to CI pipeline
  color: 4e4c5c
- name: style
  description: Improvements to code style
  color: 4e4c5c
- name: refactor
  description: Improvements to code structure
  color: 4e4c5c
- name: perf
  description: Improvements to code performance
  color: 4e4c5c

# Fix/patch labels
- name: fix
  description: Fixing something broken
  color: db4f4f
- name: revert
  description: Reverting something broken
  color: db4f4f

# Workflow status labels
- name: WIP
  description: Unfinished and not ready to merge
  color: eeeeee
- name: ">Rejected/wontmerge"
  description: Prohibit PR from being merged
  color: de4e4e
- name: ">Rejected/wontfix"
  description: This will not be worked on
  color: de4e4e
- name: ">Rejected/duplicate"
  description: This issue or pull request already exists
  color: de4e4e
