---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Breaking Changes"
    labels:
      - "semver:breaking"
  - title: "Implemented enhancements"
    labels:
      - "semver:feature"
      - feat
      - test
      - refactor
      - perf
  - title: "Fixed bugs"
    labels:
      - "semver:patch"
      - fix
      - revert
  - title: "Docs Updates"
    labels:
      - docs
  - title: "Misc. Improvements"
    labels:
      - chore
      - ci
      - style

change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"

version-resolver:
  major:
    labels:
      - "semver:breaking"
  minor:
    labels:
      - "semver:feature"
  patch:
    labels:
      - "semver:patch"
  default: patch

template: |
  # Changes since $PREVIOUS_TAG

  $CHANGES

  ## Contributors to this Release

  $CONTRIBUTORS
