name: Tag a new release using Semantic Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  tag_release:
    name: Tag a new release
    runs-on: ubuntu-latest

    steps:
      # Don't generate a new release if PR still has WIP label
      - name: Prohibit WIP labels
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "WIP"
      # Don't generate a new release if PR was closed with a
      # wontmerge, wontfix, or duplicate label
      - name: Prohibit merge-blocking labels
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "wontmerge, wontfix, duplicate"

      # Action for generating tag release can be found at
      # https://github.com/marketplace/actions/semver-release
      - name: Generate release tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
          tag_format: "v%semver:breaking%.%semver:feature%.%semver:patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
