name: Tag a new release using Semantic Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  tag_release:
    name: Tag a new release
    runs-on: ubuntu-latest

    steps:

      # Action for generating tag release can be found at
      # https://github.com/marketplace/actions/semver-release
      - name: Generate release tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
          tag_format: "v%semver:breaking%.%semver:feature%.%semver:patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
