name: Tag a new release using Semantic Versioning

on:
  push:
    branches:
      - master
  # pull_request:
  #   types:
  #     - synchronize
  #     - closed
  #     - opened
  #     - edited

jobs:
  draft_release:
    name: Update the next release draft for the project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Draft a new GitHub release
        id: semver
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELNOTES: ${{ steps.relnotes.outputs.release_notes }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install changelog generator
        run: gem install github_changelog_generator
      - name: Run changelog generator
        id: relnotes
        run: |
          .github/scripts/generate_release_notes.sh

          # cat .tmp/RELEASE_NOTES.md
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_TAG: ${{ steps.semver.outputs.tag_name }}

      # - name: Generate changelog for release
      #   id: release-changelog
      #   run: |
      #     docker pull ferrarimarco/github-changelog-generator

      # - name: Generate changelog for release
      #   id: release-changelog
      #   uses: heinrichreimer/action-github-changelog-generator@v2.1.1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     dateFormat: "%Y-%m-%d"
      #     pullRequests: true
      #     prWoLabels: true
      #     author: true
      #     stripGeneratorNotice: true
      #     output: ""
      #     breakingLabel: "## Breaking changes"
      #     breakingLabels: "semver:breaking"
      #     enhancementLabel: "## Implemented enhancements"
      #     enhancementLabels: "semver:feature,feat,docs,test,refactor,perf"
      #     bugsLabel: "## Fixed bugs"
      #     bugLabels: "semver:patch,fix,revert"
      #     # futureRelease: "${{ env.SEMVER_TAG }}"
      #   env:
      #     SEMVER_TAG: ${{ steps.semver.outputs.tag_name }}
          # addSections: >
          #   {
          #     "choreChanges": {
          #       "prefix": "## Misc. Improvements",
          #       "labels": [
          #         "chore",
          #         "ci",
          #         "style"
          #       ]
          #     }
          #   }

  # tag_release:
  #   name: Tag a new release
  #   runs-on: ubuntu-latest

  #   steps:
      # Don't generate a new release if PR still has WIP label
      # - name: Prohibit WIP labels
      #   uses: mheap/github-action-required-labels@v1
      #   with:
      #     mode: exactly
      #     count: 0
      #     labels: "WIP"

      # Don't generate a new release if PR was closed with a
      # wontmerge, wontfix, or duplicate label
      # - name: Prohibit merge-blocking labels
      #   uses: mheap/github-action-required-labels@v1
      #   with:
      #     mode: exactly
      #     count: 0
      #     labels: "wontmerge, wontfix, duplicate"

      # # Action for generating tag release can be found at
      # # https://github.com/marketplace/actions/semver-release
      # - name: Generate release tag
      #   id: semver
      #   uses: K-Phoen/semver-release-action@master
      #   with:
      #     release_branch: master
      #     release_strategy: none
      #     tag_format: "v%semver:breaking%.%semver:feature%.%semver:patch%"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
